language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "PyRFWyCsqM+H2GZyeBEeKH5ikHSEQEG/VaA4MhqLO0Ds1VyyIXMyur+CoKrNHrP8AWd3WF6GHCeCqqXoPDDz44aFrX9wFJ4psGjMPNqo5WAFmuPlehphGnpabYcfBcWwmTu5+gUjdxoWw1aGybfw4nXlD+E6dFcOqI1uqDIZ8hfaTs1YrIZszTSVeWWBEFwiVqfNq3aSS9OkioYmzR4H+3MruBeCVpnC5KGfC+17v+T9JSdr4Km5HN8TfeuOg5N8Lp1ZWRtxTk55bknSe6ejbpxGmMjDtngdYicR73OyI7GtfGVJ/PPCjtd+71MtfTKVLGKbAmaMqis/mhDU76m61M6XMU4V7D2UCv23nCxG8dU93+4BElJlyzyVPtlNZoHiPVpEdjd84gF3g/s1l3huwnhNERBmHovmAhCXwCYYJRsDIyeWZ5kvY6VcxQoBRdT0FD/10PW/ZCacdX31eR0I2ow/KWsZ0o/Cc16FfLJQ4elFZIzGCdcqRxJouGu3WEqDYnijP5XISnhmjTjAcz9BqCo8z3zUBJ8sK9WPIZK7UhI2sD4iC5FJ0oaavw7uMx1xG2Qpgxa5QBa25UuZ0L4lAyJP/XFRy+t7naP5qIHGHmR6rxbaTSkNZIrUYrmj3aFhq7jIaMmQquypvVfoP91Gm5TdQSvE8xRyRuEmPFRzH6w="
