language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js

env:
  secure: "lcsIhMcOum+KVKpDTVfZGAZ3HhJniTmk8aOqXdpzN7/mZB65mFuW7kLLIIgjkFHWfQ/zRDZFmiqkda26FK2VrF6Nct7N8Q9hyLKJC4PIoaCftABTBRmEGmkdRewKI4XSLLH1tT41huPLZyp42GXVcSKrvjXbfH1yBMDRYtkurBEAPoJQ8DC4Xsui0DYgm6EH286kcCAVqmJyws4573vQQEGU3uUc1vzrT4Q4Q+Q28a4Cu/NFwELU0TtKzl6ldZM68MgTKtb+yDdO89lDnKI+Ay2lmL25NSoexqO87DYN9AVIdtPTVXsWs12eOQdpO+UttKUZZS8/HrM5LmG/zBP51FXatmoz/52+3dWpVyMwUsRfSxChZNJ/Mep8eHKKBXybZb0lPO66Csg11gzPDQBWcgpjElhF7UAI3ySAKzIX2RbI78gFr04rZwd55yoFcMgcr7z991pDZwJ0uYTwY/XSEk5Rar9PGvYqsR5bXd6LhjhjKA/s32G/AVuoc6mGWEgjAsEYiH2lygObefB4rhDZZWKTRpjo7LoGt6/wnree0R7Dp1r23B7SIizQxQK3vYJJ13uCVjzG+vPIU4sWcznsO5N79Ag5HW4Z0csucoytaR9hezDnnvYe+0ImaY5zYNb9lvOcP4PpaI1CbvOIdaGDq9VDA1gIN75fgQRl+GE7ZTQ="
