language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "dihLuJJub4oTvCpWGLYVx6f+oiM63hSPNP28PhHp/NjYHrYVn7m/YBbUQpVWbnV3ZkUDfhXK24hF0ESq9ghdujGjj4b4n6WoMLuGmVZthH4KL2v/+JgHD9yaGAxFs7fR82wGpq+FeHbvj6pwYNeoKxL6Z/c+jdXUyWlsr4jRob51+hg/1hGTvnonJovBXcs/4aFZTrQ8rPARDfeSaS2bnL8lCRBwjoPh/9cxWh7tfAHOtN2n2vPXQZBJiZAOo0tibW+zcVIl8qim+I0+vAdXAUlPysQJ3bgChh0Hgn0iSZyuSEKW0tBFPy0s3nkHL9NNfLI+rPfNJiugAFfEFJlXElUmk0Isv5LjvFdPjb3N973fQu5tns3pWp5+8k7yYDJgnVIQ2l3sDsaOorKswLqsBF0gQnolC0Ev528j2Hjckjw1hUVX5GKWBojGr+gLcpd/YwcMzTkvfbdx/c8xkaT8s2Vngcm+hsAb5oymf7JP7ltVNhjKNMuicNaPsOuxW8xYBWDXnl7jby+Vf1pFXHRdqhbS16YdJIAokMl9vtO4tg3vy5SKh3F0fNQE/p5T3+K8v1NWLyABK9tac9i5efOVsnIbDM+VQAJ9IKoNCW/gaGYf6l/OcnQ1DH2gM/qM2ortxME02cDzssecuKTiNZM1QlIa1ecZlZ4Gw9LANe1om/I="
