language: node_js
node_js:
- '6'
before_install:
# TODO OSS
# - npm i npm-cli-login -g
# - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
# - npm who
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "fzHjMBOGxjCZSL6wJYtF9tL40I4dDs7ndvoQMO9LlYsPR+idmgrmMA4MnDo8TLE3qI8LZcocb+jYP6Zj3ZKma9wyr8236myXsA78QqMLTbvzmCHfbULiTSVI517cj9bmqqFvNGAWyYN4iUr+XucTP7Hq+3N61Ot/PD5WceF4UgqGD2o0G27edyD5JxtdPfXvKL81Q4DE2p2nGENOhzxo5k/jJQrQ6TUweHtY58nqe50f98mpn6e8MfgYSKWImMS5nvFp149aJmlrQAtu/RqttNLUdzSFYWt/jAs8Ep0w/aTOX2MiwzgwzFCIJw0vtxuUf7d4vDtSIrUjyWZutKciIMuYInN4J/8hOrLkwxz9G6V/dSANnQJEnHasJBJeYebrwqrvFYNdZwswSQgI8H+6WRXCaNoJ6yNqhxyc30d6whjn+S2Fy/BsUa9QCFHZynMXE0j5OAwMWxrMu1C8l35e9nKXYWghb5Eu/rivkffEPM4GgO8Z1lFcHyZqYTW+e0SAc16GXjSYigIn6vd+4VRMouzUERX8LhSgzdmxhiMGSUz/wNm0xI2c4jV4cmB0M6lA3bzEVyhcQwRQeZL+zPi8y/YoM3dvihcWPKz8VKiRDBbkDcbYK7UkwAc452TOIht43w8HUd9qSohmvO2SS2qb1r3gdDqkQGZhMbtisSgi4QY="
